/**
 * Typed accessor for the compiled content bundle.
 *
 * The bundle is generated by `tools/content-compiler` into `generated/`;
 * that directory is never hand-edited (TDD section 4). This Node-side loader
 * validates the bundle on read; the browser build will import the bundle
 * statically once the web shell needs it (Stage 2).
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { validateCompiledContent, type CompiledContent } from "@neolab/content-schema";

const generatedDir = join(fileURLToPath(import.meta.url), "..", "..", "generated");

export function loadCompiledContent(): CompiledContent {
  let text: string;
  try {
    text = readFileSync(join(generatedDir, "content.bundle.json"), "utf8");
  } catch {
    throw new Error(
      "Compiled content bundle not found. Run `pnpm content:build` first.",
    );
  }
  return validateCompiledContent(JSON.parse(text));
}
