/**
 * Typed accessor for the compiled content bundle.
 *
 * The bundle is generated by `tools/content-compiler` into `generated/`;
 * that directory is never hand-edited (TDD section 4). Until the compiler
 * emits a real bundle this loader throws a descriptive error.
 */
export interface CompiledContentStub {
  readonly manifest: {
    readonly contentVersion: string;
    readonly bundleHash: string;
  };
}

import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

export function loadCompiledContent(): CompiledContentStub {
  // Deliberately a runtime require so a missing bundle produces a clear
  // "run pnpm content:build" message instead of a bundler resolution error.
  try {
    const bundle: unknown = require("../generated/content.bundle.json");
    return bundle as CompiledContentStub;
  } catch {
    throw new Error(
      "Compiled content bundle not found. Run `pnpm content:build` first.",
    );
  }
}
