/**
 * Typed accessor for the compiled content bundle.
 *
 * The bundle is generated by `tools/content-compiler` into `generated/`;
 * that directory is never hand-edited (TDD section 4). This Node-side loader
 * validates the bundle on read; the browser build will import the bundle
 * statically once real content lands (Stage 1+).
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { compiledBundleSchema, type CompiledBundle } from "@neolab/content-schema";

const generatedDir = join(fileURLToPath(import.meta.url), "..", "..", "generated");

export function loadCompiledContent(): CompiledBundle {
  let text: string;
  try {
    text = readFileSync(join(generatedDir, "content.bundle.json"), "utf8");
  } catch {
    throw new Error(
      "Compiled content bundle not found. Run `pnpm content:build` first.",
    );
  }
  const parsed = compiledBundleSchema.safeParse(JSON.parse(text));
  if (!parsed.success) {
    throw new Error(
      `Compiled content bundle is invalid (regenerate with \`pnpm content:build\`): ${parsed.error.issues
        .slice(0, 3)
        .map((issue) => `${issue.path.join(".")}: ${issue.message}`)
        .join("; ")}`,
    );
  }
  return parsed.data;
}
