export {
  advanceResearch,
  calculateDomainOutput,
  calculateResearchOutputModifier,
  chooseGenericAdvance,
  climbResearchLadder,
  reconcileGenericAdvanceModifiers,
  researchPointsForNextLevel,
  type ResearchOutputModifierBreakdown,
  type ResearchGenerationLine,
  type ResearchOutputBreakdown,
} from "./research.ts";
export {
  advancePaperRace,
  calculatePaperPublicationAura,
  calculatePaperPublicationScore,
  choosePublicationPolicy,
  describePaperScientificPayload,
  describePaperUnlockEffect,
  paperMechanicalBenefits,
  derivePaperBreakthroughChance,
  derivePaperFocusProgrammeIds,
  deriveRivalPublicationChance,
  describePaperRaceStanding,
  paperRequiredLevel,
  isPublicPaperDiscovery,
  labKnowsPaper,
  listEligiblePapers,
  reconcilePaperBenefits,
  type EligiblePaper,
  type PaperBreakthroughCheck,
} from "./papers.ts";
