export {
  calculateInterventionPressure,
  detectGovernmentCrisisTriggers,
  GOVERNMENT_SEGMENT_ID,
  isNationalisationEligible,
  quoteLobbyingProject,
  resolveGovernmentIntervention,
  startLobbyingProject,
  synchroniseGovernmentEventResponses,
  GOVERNMENT_PROGRAMMES,
  PROGRAMME_EXIT_TRUST_COST,
  governmentAttentionTarget,
  governmentProgrammeEndgameBenefits,
  governmentProgrammeQuarterlyGrant,
  joinGovernmentProgramme,
  leaveGovernmentProgramme,
  quoteGovernmentProgramme,
  quoteGovernmentProgrammeExit,
  settleGovernmentProgrammes,
  updateGovernmentQuarter,
  updateGovernmentWeekly,
  type GovernmentTriggerCandidate,
  type GovernmentProgrammeEndgameBenefits,
  type GovernmentProgrammeExitQuote,
  type LobbyingProjectQuote,
} from "./politics.ts";
