/**
 * Public surface of the simulation package (TDD section 33.1).
 *
 * The web app may import ONLY from `@neolab/sim/public`. Everything else in
 * `src/**` is internal and enforced by lint rules.
 *
 * Engine transitions still return canonical state for the browser runtime,
 * but components and stores consume only the player-safe `projectGameView`
 * projection. The web architecture boundary and recursive hidden-key tests
 * prevent raw state from becoming a UI data source.
 */
export const SIM_PACKAGE = "@neolab/sim";

export {
  modifierEffectPreview,
  modifierTargetDisplayLabel,
  weeklyProgressVariationScope,
} from "./presentation/modifier-copy.ts";
export { createNewGame, type NewGameConfig } from "./engine/create-new-game.ts";
export {
  createProgressiveNewGame,
  labMaturityDefinition,
  type LabMaturityStage,
  type LabMaturityViewData,
} from "./campaign/lab-maturity.ts";
export { createGuidedTutorialGame } from "./tutorial/guided-tutorial.ts";
export {
  advanceOneTick,
  type TickInstrumentation,
  type TickSystemTiming,
} from "./engine/advance-tick.ts";
export {
  detectEndgameTrigger,
  endgameClockStopReason,
  endingConsequenceForId,
  isCanonicalEndingId,
  SAFEST_ENDING_MAX_DECEPTIVE_INTENT,
  type EndgameClockStopReason,
  type EndgameTrigger,
  type EndingConsequence,
} from "./endgame/index.ts";
export {
  FRONTIER_PHASE_FRONTIER_CAPABILITY,
  SCALING_PHASE_FRONTIER_CAPABILITY,
} from "./engine/world-progression.ts";
export {
  TERAFLOPS_PER_TRAINING_FACTOR,
  formatTeraflops,
  formatTotalFlop,
  generationTeraflopsPerGpu,
  totalFlopInvested,
} from "./compute/flops.ts";
export type { TransitionAudit, TransitionResult } from "./engine/transaction.ts";
export type { DomainEvent } from "./engine/domain-events.ts";
export type { AutoPauseReason } from "./model/state.ts";
export {
  applyCommand,
  CommandRejectedError,
  validateCommand,
  type CommandMeta,
  type CommandPreview,
  type CommandValidation,
  type GameCommand,
  type ChooseGenericAdvanceCommand,
  type ChoosePublicationPolicyCommand,
  type StartTrainingRunCommand,
  type StartEvaluationCommand,
  type DismissAnomalyCommand,
  type InvestigateAnomalyCommand,
  type RespondToDecisionEventCommand,
  type StartProductisationCommand,
  type SetModelDeploymentPolicyCommand,
  type AssignResearcherCommand,
  type RecruitResearcherCommand,
  type StartResearcherCommitmentCommand,
  type SubmitRetentionOfferCommand,
  type ResolveResearcherUltimatumCommand,
  type DismissResearcherCommand,
  type ReviewRivalRaceCommand,
  type RuleViolation,
  type SetGpuAllocationCommand,
  type BuyGpusCommand,
  type StartFundraisingCampaignCommand,
  type AcceptFundingOfferCommand,
  type StartLobbyingProjectCommand,
  type StartAgiComponentCommand,
  type SetModelAutonomyCommand,
  type JoinGovernmentProgrammeCommand,
  type LeaveGovernmentProgrammeCommand,
  type ConductRivalDiplomacyCommand,
  type ProposeCoalitionCommand,
  type StartCoalitionProjectCommand,
  type RatifyCoalitionCommand,
  type SetCandidateAccessCommand,
  type IsolateCandidateArtifactCommand,
  type ResolveCandidateIncidentCommand,
  type NominateCandidateCommand,
  type CommitCapabilityProofCommand,
  type CommitCandidateSafetyResponseCommand,
  type ResolvePressureCollisionCommand,
  type EnterFinalReviewCommand,
  type ChooseDeploymentModeCommand,
  type ResolveRolloutDecisionCommand,
  type ResolveContainmentFailureCommand,
  type ConfigureCandidateRetirementCommand,
  type TransmitCandidateRetirementCommand,
  type ChoosePostRetirementPathCommand,
  type ChooseFalseDawnPathCommand,
  type TransmitDeploymentCommand,
  type AdvanceWorldWaitingCommand,
  type SellGpusCommand,
  type SetPublicPriceCommand,
  type StartFacilityConstructionCommand,
} from "./commands/index.ts";
export {
  AGI_COMPONENT_RULES,
  AGI_COMPONENT_TYPES,
  quoteAgiComponent,
  type AgiComponentQuote,
  type AgiComponentRule,
} from "./endgame/candidate-programme.ts";
export {
  CANDIDATE_ACCESS_RULES,
  candidateAccessAcceleration,
  quoteCandidateAccess,
  type CandidateAccessQuote,
  type CandidateAccessRule,
  isolateCandidateArtifact,
  quoteCandidateIncidentReview,
  quoteCandidateIsolation,
  resolveCandidateIncident,
  type CandidateIncidentReviewQuote,
  type CandidateIsolationQuote,
} from "./endgame/index.ts";
export {
  PRESSURE_COLLISIONS,
  calculateCrisisProjectCapacity,
  type CrisisProjectQuote,
  type CrisisProjectCapacity,
  DEPLOYMENT_MODE_RULES,
  quoteDeploymentMode,
  type DeploymentModeQuote,
  CAPABILITY_CHALLENGE_RULES,
  CAPABILITY_VERIFIER_RULES,
  quoteCapabilityProof,
  candidateDossier,
  deploymentStrategies,
  deploymentConfirmationPhrase,
  quoteDeploymentTransmission,
  rolloutDecisionOptions,
  type CapabilityChallengeId,
  type CapabilityVerifierId,
  type CapabilityProofQuote,
  type CandidateDossier,
  type CandidateSafetyResponse,
  type CandidateSafetyResponseId,
  type DossierFinding,
  type DeploymentStrategy,
  type DeploymentStrategyId,
  type DeploymentTransmissionQuote,
  type RolloutDecisionOption,
} from "./endgame/index.ts";
export {
  quoteResearcherAssignment,
  type ResearcherAssignmentInput,
  type ResearcherAssignmentQuote,
  quoteRecruitment,
  type RecruitmentQuote,
  quoteDismissal,
  quoteRetentionOffer,
  quoteUltimatumResponse,
  type DismissalQuote,
  type RetentionOfferInput,
  type RetentionOfferPreview,
  type UltimatumResponse,
  type UltimatumResponsePreview,
} from "./researchers/index.ts";
export {
  TRAINING_POSTURES,
  quoteTrainingRun,
  TRAINING_DEFAULT_ERA_GPUS,
  TRAINING_DEFAULT_WEEKS,
  TRAINING_MAX_WEEKS,
  TRAINING_MIN_ERA_GPUS,
  TRAINING_MIN_WEEKS,
  classifyTrainingRun,
  trainingEraGpuWeeks,
  forecastTrainingIntrinsicSafety,
  trainingPostureDefinition,
  type TrainingPostureDefinition,
  type TrainingQuote,
  type TrainingIntrinsicSafetyForecast,
  type TrainingRequest,
} from "./training/index.ts";
export {
  AGI_CANDIDATE_MINIMUM_CAPABILITY_ATTRIBUTE,
  AGI_CANDIDATE_MINIMUM_FRONTIER_CAPABILITY,
  capabilityScoreForDisplay,
  calculateFrontierCapability,
  classifyCapabilityTier,
  isApparentAgiCandidate,
  quoteStandingAutonomy,
  STANDING_AUTONOMY_REQUIREMENTS,
  superintelligenceProbability,
  type CapabilityTierView,
} from "./models/index.ts";
export {
  quoteAnomalyAction,
  quoteEvaluation,
  SAFETY_PRACTICE_DOSSIER_XP_BY_TIER,
  safetyPracticeProfile,
  safetyPracticeXpForEvaluation,
  type AnomalyActionQuote,
  type EvaluationQuote,
  type EvaluationRequest,
  type SafetyPracticeLevel,
  type SafetyPracticeProfile,
} from "./evaluations/index.ts";
export {
  quoteDeploymentAura,
  quoteProductisation,
  type DeploymentAuraPreview,
  type ProductisationQuote,
  type ProductisationRequest,
} from "./productisation/index.ts";
export { seed128, type Seed128 } from "./random/seed.ts";
export type {
  AnomalyId,
  EvaluationId,
  EventInstanceId,
  FacilityId,
  FundingOfferId,
  CoalitionId,
  LabId,
  ModelId,
  ProjectId,
  ResearcherId,
} from "./model/ids.ts";
export { SCORE_CATEGORY_IDS } from "./engine/score.ts";
export {
  calculateCoalitionAssetUniqueness,
  evaluateCoalitionEligibility,
  quoteCoalitionProject,
  quoteCoalitionProposal,
  COALITION_DISABLED_REASON,
  COALITION_MECHANIC_ENABLED,
  COALITION_PROJECT_RULES,
  type CoalitionEligibility,
  type CoalitionEligibilityCheck,
  type CoalitionProjectQuote,
  type CoalitionProposalQuote,
} from "./coalition/index.ts";
export type {
  CoalitionAssetKind,
  CoalitionProjectType,
  CoalitionStatus,
  CrisisProjectType,
  DeploymentModeId,
  ProsperityProgrammeId,
  RolloutDecisionOptionId,
} from "./model/state.ts";
export {
  PROSPERITY_PROGRAMMES,
  PROSPERITY_PROGRAMME_IDS,
  bestProsperityProgramme,
  deriveProsperityProgrammes,
  findProsperityProgramme,
  type ProsperityProgrammeDefinition,
  type ProsperityProgrammeReadiness,
} from "./prosperity/index.ts";
export {
  calculateOpportunityChance,
  collectMandatoryTriggers,
  listEligibleEventDefinitions,
  formatEventMessage,
  previewEventOption,
  type EventOptionPreview,
  type TriggerCandidate,
  type WeightedEventCandidate,
  type EventMessageTokens,
} from "./events/index.ts";
export {
  calculateFundingScore,
  hasInsolvencyRescuePath,
  OPENING_SEED_MINIMUM_CASH_MILLIONS,
  quoteOpeningSeedRecapitalisation,
  quoteFundingOffer,
  quoteFundraisingCampaign,
  type FundingOfferQuote,
  type FundraisingCampaignQuote,
  type OpeningSeedRecapitalisationQuote,
} from "./fundraising/index.ts";
export {
  calculateInterventionPressure,
  detectGovernmentCrisisTriggers,
  GOVERNMENT_SEGMENT_ID,
  isNationalisationEligible,
  quoteLobbyingProject,
  GOVERNMENT_PROGRAMMES,
  governmentProgrammeEndgameBenefits,
  governmentProgrammeQuarterlyGrant,
  quoteGovernmentProgramme,
  quoteGovernmentProgrammeExit,
  type GovernmentProgrammeEndgameBenefits,
  type GovernmentProgrammeExitQuote,
  type GovernmentTriggerCandidate,
  type LobbyingProjectQuote,
} from "./politics/index.ts";
export {
  calculateScoreView,
  projectGameView,
  projectEndgameView,
  projectMoratoriumForecastView,
  type EvidenceAccessIndex,
  type AuraView,
  type DecisionLogEntryView,
  type AnomalyView,
  type EvaluationReportView,
  type EventQueueItemView,
  type EventQueueOptionView,
  type EventQueueView,
  type FacilitiesView,
  type FinanceView,
  type FundraisingView,
  type CampusConstructionStage,
  type CampusConstructionView,
  type CampusFacilityView,
  type CampusLoadState,
  type CampusPersonView,
  type CampusSceneCueView,
  type CampusView,
  type PeopleAbilityEffectView,
  type PeopleAbilityView,
  type PeopleBenefitRowView,
  type PeopleAssignmentOptionView,
  type PeopleCompactConditionView,
  type PeopleCompactDestination,
  type PeopleConditionBand,
  type PeopleProfileView,
  type PeopleResearchSkillView,
  type PeopleView,
  type RosterResearcherView,
  type TalentCandidateView,
  type RealPaperCitation,
  type ResearcherPaperCredit,
  type GameView,
  type CrisisClockView,
  type EndgameView,
  type MoratoriumForecastView,
  type GpuAllocationLineView,
  type GpuFleetView,
  type LabIdentityView,
  type MarketView,
  type PoliticsView,
  type AutonomyUnlockPresentationQueueItemView,
  type SafetyPracticeBenefitsView,
  type SafetyPracticeLevelPresentationQueueItemView,
  type CapabilityTierPresentationQueueItemView,
  type CapabilityProofResultPresentationQueueItemView,
  type EndgameReturnPresentationQueueItemView,
  type MoratoriumResultPresentationQueueItemView,
  type RivalCandidateSetbackPresentationQueueItemView,
  type ModelIncidentPresentationQueueItemView,
  type CandidateContainmentIncidentPresentationQueueItemView,
  type LabMaturityUnlockPresentationQueueItemView,
  type PresentationQueueItemView,
  type ModelCardView,
  type ModelsView,
  type PlayerKnowledgeContext,
  type ProjectView,
  type ResearchProgramView,
  type ResearchPaperView,
  type ResearchView,
  type ProsperityProgrammeView,
  type ProsperityView,
  type ScoreView,
  type ScoreCategoryView,
  type ScoreEntryView,
  type TopBarView,
  type TrainingLossCurveView,
  type TrainingLossPointView,
  type TrainingLossTelemetryView,
  type CoalitionBoardView,
  type RivalWorldView,
  type WorldView,
} from "./selectors/index.ts";
export {
  calculateGpuThroughput,
  normaliseAllocation,
  planGpuPortfolio,
  resolveGpuReservations,
  type GpuAllocationPlan,
  type GpuPortfolioPlan,
  type GpuSelection,
  type GpuThroughputBreakdown,
  type GpuWorkload,
  type ProgramGpuAllocation,
  type ReservationPlan,
  calculateGpuFinanceCosts,
  quoteGpuPurchase,
  quoteGpuSale,
  sellGpus,
  unlockedGpuGenerationIds,
  GPU_RESALE_FRACTION,
  GPU_TRADE_UNIT,
  type GpuFinanceCosts,
  type GpuPurchaseQuote,
  type GpuSaleQuote,
  type GpuCapacityRequirement,
} from "./compute/index.ts";
export {
  NEGATIVE_CASH_BANKRUPTCY_WEEKS,
  calculateRunway,
  formatValuation,
  forecastFinance,
  type FinanceForecast,
  type RunwayView,
} from "./finance/index.ts";
export {
  AURA_MARKET_PRESSURE_PER_CAPABILITY_POINT,
  calculateAuraGain,
  calculateAuraSignal,
  quoteAuraMarketPressure,
  type AuraGainBreakdown,
  type AuraMarketPressureQuote,
  type AuraSignalBreakdown,
} from "./aura/index.ts";
export {
  projectRivalPublicSignals,
  projectRivalRelationships,
  projectRivalCandidateCountdowns,
  quoteRivalDiplomacy,
  RIVAL_DIPLOMACY_DISABLED_REASON,
  RIVAL_DIPLOMACY_ENABLED,
  RIVAL_DIPLOMACY_RULES,
  type RivalDiplomacyQuote,
  type RivalPublicSignalView,
  type RivalRelationshipBand,
  type RivalRelationshipView,
  type RivalCandidateCountdownView,
} from "./rivals/index.ts";
export type { RivalDiplomacyAction } from "./model/state.ts";
export {
  PUBLIC_PRICE_TIERS,
  SERVING_AURA_LADDER,
  calculateSegmentAppeal,
  calculateServingDemandCap,
  deliveredFlopValueMultiplier,
  forecastUsage,
  globalRevenueOpportunityMillionsPerCycle,
  globalServingDemandTeraflops,
  isMarketSegmentUnlocked,
  servingAuraForUsage,
  type AppealBreakdown,
  type SegmentUsageForecast,
  type ServingDemandCap,
  type UsageForecast,
} from "./market/index.ts";
export {
  calculateFacilityCapacity,
  quoteFacilityConstruction,
  type ConstructionQuote,
  type FacilityCapacityView,
} from "./facilities/index.ts";
export { calculateProjectCapacity, type ProjectCapacityView } from "./projects/index.ts";
export {
  createSaveEnvelope,
  loadSaveEnvelope,
  MAX_SAVE_IMPORT_BYTES,
  MemorySaveRepository,
  MemoryHighScoreRepository,
  migrateSaveState,
  parseImportedSaveBlob,
  saveMetadataFromEnvelope,
  SAVE_MIGRATIONS,
  SaveLoadError,
  stateHash,
  createHighScoreEntry,
  compareHighScores,
  entriesForBoard,
  HIGH_SCORE_BOARD_LIMIT,
  type HighScoreBoard,
  type HighScoreEntry,
  type HighScoreRepository,
  type LeaderboardSubmissionV1,
  type LoggedCommand,
  type LoadSaveResult,
  type ImportSaveResult,
  type MigrationContext,
  type SaveEnvelopeV1,
  type SaveMigration,
  type SaveMigrationResult,
  type SaveMetadata,
  type SaveRepository,
  type WriteSaveRequest,
} from "./persistence/index.ts";
export type { PlayerSafetyAssessment } from "./safety/player-safety-assessment.ts";
